import { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { useSearchParams, useNavigate } from 'react-router-dom';
import api from '../lib/api';
const C={p:'#059669',s:'#0f172a',m:'#64748b',bg:'#fafbfc'};
export default function ResetPasswordPage(){
  const{t}=useTranslation();
  const[params]=useSearchParams();const navigate=useNavigate();
  const token=params.get('token');const[pw,setPw]=useState('');const[confirm,setConfirm]=useState('');const[loading,setLoading]=useState(false);const[done,setDone]=useState(false);const[error,setError]=useState('');const[valid,setValid]=useState(true);
  useEffect(()=>{if(!token)setValid(false);},[token]);
  const handleSubmit=async(e)=>{e.preventDefault();if(pw!==confirm){setError(t('resetPwd.mismatch'));return;}setLoading(true);try{await api.request('/auth/reset-password',{method:'POST',body:JSON.stringify({token,password:pw})});setDone(true);setTimeout(()=>navigate('/login'),3000);}catch(err){setError(err.message||t('common.error'));}setLoading(false);};
  if(!valid)return(<div style={{minHeight:'100vh',display:'flex',alignItems:'center',justifyContent:'center',padding:24,background:C.bg}}><div style={{maxWidth:440,width:'100%',textAlign:'center',background:'#fff',borderRadius:24,padding:48,boxShadow:'0 20px 60px rgba(0,0,0,0.08)'}}><div style={{fontSize:52,marginBottom:16}}>🔐</div><h2 style={{fontWeight:800,fontSize:24,color:C.s,marginBottom:12}}>{t('resetPwd.invalid_title')}</h2><p style={{color:C.m,marginBottom:32}}>{t('resetPwd.invalid_subtitle')}</p><a href="/forgot-password" style={{display:'inline-block',padding:'12px 24px',borderRadius:12,background:C.p,color:'#fff',fontWeight:700,textDecoration:'none'}}>{t('resetPwd.request_new')}</a></div></div>);
  if(done)return(<div style={{minHeight:'100vh',display:'flex',alignItems:'center',justifyContent:'center',padding:24,background:C.bg}}><div style={{maxWidth:440,width:'100%',textAlign:'center',background:'#fff',borderRadius:24,padding:48,boxShadow:'0 20px 60px rgba(0,0,0,0.08)'}}><div style={{fontSize:52,marginBottom:16}}>✅</div><h2 style={{fontWeight:800,fontSize:24,color:C.s,marginBottom:12}}>{t('resetPwd.success_title')}</h2><p style={{color:C.m,marginBottom:24}}>{t('resetPwd.redirect')}</p><a href="/login" style={{color:C.p,fontWeight:700,textDecoration:'none'}}>{t('resetPwd.login_now')}</a></div></div>);
  return(<div style={{minHeight:'100vh',display:'flex',alignItems:'center',justifyContent:'center',padding:24,background:C.bg}}><div style={{width:'100%',maxWidth:440,background:'#fff',borderRadius:24,padding:48,boxShadow:'0 20px 60px rgba(0,0,0,0.08)'}}><h1 style={{fontWeight:800,fontSize:28,color:C.s,margin:'0 0 32px'}}>{t('resetPwd.title')}</h1><form onSubmit={handleSubmit}><div style={{marginBottom:16}}><label style={{display:'block',fontWeight:600,fontSize:13,color:C.s,marginBottom:8}}>{t('resetPwd.new_pwd')}</label><input type="password" value={pw} onChange={e=>setPw(e.target.value)} required style={{width:'100%',padding:'14px 16px',borderRadius:12,border:'1.5px solid #e2e8f0',background:C.bg,fontSize:15,color:C.s,outline:'none',boxSizing:'border-box'}}/></div><div style={{marginBottom:16}}><label style={{display:'block',fontWeight:600,fontSize:13,color:C.s,marginBottom:8}}>{t('resetPwd.confirm_pwd')}</label><input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} required style={{width:'100%',padding:'14px 16px',borderRadius:12,border:'1.5px solid #e2e8f0',background:C.bg,fontSize:15,color:C.s,outline:'none',boxSizing:'border-box'}}/></div>{error&&<p style={{color:'#dc2626',fontSize:13,marginBottom:12}}>{error}</p>}<button type="submit" disabled={loading} style={{width:'100%',padding:15,borderRadius:12,border:'none',background:loading?'#94a3b8':C.p,color:'#fff',fontWeight:700,fontSize:15,cursor:loading?'not-allowed':'pointer'}}>{loading?t('resetPwd.submitting'):t('resetPwd.submit')}</button></form></div></div>);
}