import { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { useSearchParams, useNavigate } from 'react-router-dom';
import api from '../lib/api';
const C={p:'#059669',s:'#0f172a',m:'#64748b',bg:'#fafbfc'};
export default function SetupPasswordPage(){
  const{t}=useTranslation();
  const[params]=useSearchParams();const navigate=useNavigate();
  const token=params.get('token');const[pw,setPw]=useState('');const[loading,setLoading]=useState(false);const[checking,setChecking]=useState(true);const[valid,setValid]=useState(false);const[partnerName,setPartnerName]=useState('');const[done,setDone]=useState(false);const[error,setError]=useState('');
  useEffect(()=>{if(!token){setChecking(false);return;}api.request(`/auth/verify-invite?token=${token}`).then(d=>{setValid(true);setPartnerName(d.name||'');}).catch(()=>setValid(false)).finally(()=>setChecking(false));},[token]);
  const handleSubmit=async(e)=>{e.preventDefault();setLoading(true);try{await api.request('/auth/setup-password',{method:'POST',body:JSON.stringify({token,password:pw})});setDone(true);setTimeout(()=>navigate('/login'),3000);}catch(err){setError(err.message||t('common.error'));}setLoading(false);};
  if(checking)return(<div style={{minHeight:'100vh',display:'flex',alignItems:'center',justifyContent:'center',background:C.bg}}><p style={{color:C.m}}>{t('setupPwd.loading')}</p></div>);
  if(!valid)return(<div style={{minHeight:'100vh',display:'flex',alignItems:'center',justifyContent:'center',padding:24,background:C.bg}}><div style={{maxWidth:440,width:'100%',textAlign:'center',background:'#fff',borderRadius:24,padding:48,boxShadow:'0 20px 60px rgba(0,0,0,0.08)'}}><div style={{fontSize:52,marginBottom:16}}>🔐</div><h2 style={{fontWeight:800,fontSize:24,color:C.s,marginBottom:12}}>{t('setupPwd.invalid_title')}</h2><p style={{color:C.m,marginBottom:32}}>{t('setupPwd.invalid_subtitle')}</p><a href="/login" style={{color:C.p,fontWeight:700,textDecoration:'none'}}>{t('setupPwd.back_to_login')}</a></div></div>);
  if(done)return(<div style={{minHeight:'100vh',display:'flex',alignItems:'center',justifyContent:'center',padding:24,background:C.bg}}><div style={{maxWidth:440,width:'100%',textAlign:'center',background:'#fff',borderRadius:24,padding:48,boxShadow:'0 20px 60px rgba(0,0,0,0.08)'}}><div style={{fontSize:52,marginBottom:16}}>🎉</div><h2 style={{fontWeight:800,fontSize:24,color:C.s,marginBottom:12}}>{t('setupPwd.success_title')}</h2><p style={{color:C.m}}>{t('setupPwd.success_text')}</p></div></div>);
  return(<div style={{minHeight:'100vh',display:'flex',alignItems:'center',justifyContent:'center',padding:24,background:C.bg}}><div style={{width:'100%',maxWidth:440,background:'#fff',borderRadius:24,padding:48,boxShadow:'0 20px 60px rgba(0,0,0,0.08)'}}><h1 style={{fontWeight:800,fontSize:28,color:C.s,margin:'0 0 8px'}}>{t('setupPwd.title')}</h1><p style={{color:C.m,margin:'0 0 32px',lineHeight:1.6}}>{t('setupPwd.subtitle')}</p><form onSubmit={handleSubmit}><label style={{display:'block',fontWeight:600,fontSize:13,color:C.s,marginBottom:8}}>{t('setupPwd.pwd_label')}</label><input type="password" value={pw} onChange={e=>setPw(e.target.value)} placeholder={t('setupPwd.pwd_ph')} required style={{width:'100%',padding:'14px 16px',borderRadius:12,border:'1.5px solid #e2e8f0',background:C.bg,fontSize:15,color:C.s,outline:'none',boxSizing:'border-box',marginBottom:16}}/>{error&&<p style={{color:'#dc2626',fontSize:13,marginBottom:12}}>{error}</p>}<button type="submit" disabled={loading} style={{width:'100%',padding:15,borderRadius:12,border:'none',background:loading?'#94a3b8':C.p,color:'#fff',fontWeight:700,fontSize:15,cursor:loading?'not-allowed':'pointer'}}>{loading?t('setupPwd.submitting'):t('setupPwd.submit')}</button></form></div></div>);
}